"""Application constants for validation and selection lists."""

from typing import Dict, List

# ============================================================================
# Countries (ISO 3166-1 alpha-2)
# ============================================================================

COUNTRIES: List[Dict[str, str]] = [
    {"code": "AF", "name": "Afghanistan"},
    {"code": "AL", "name": "Albania"},
    {"code": "DZ", "name": "Algeria"},
    {"code": "AD", "name": "Andorra"},
    {"code": "AO", "name": "Angola"},
    {"code": "AR", "name": "Argentina"},
    {"code": "AM", "name": "Armenia"},
    {"code": "AU", "name": "Australia"},
    {"code": "AT", "name": "Austria"},
    {"code": "AZ", "name": "Azerbaijan"},
    {"code": "BS", "name": "Bahamas"},
    {"code": "BH", "name": "Bahrain"},
    {"code": "BD", "name": "Bangladesh"},
    {"code": "BB", "name": "Barbados"},
    {"code": "BY", "name": "Belarus"},
    {"code": "BE", "name": "Belgium"},
    {"code": "BZ", "name": "Belize"},
    {"code": "BJ", "name": "Benin"},
    {"code": "BT", "name": "Bhutan"},
    {"code": "BO", "name": "Bolivia"},
    {"code": "BA", "name": "Bosnia and Herzegovina"},
    {"code": "BW", "name": "Botswana"},
    {"code": "BR", "name": "Brazil"},
    {"code": "BN", "name": "Brunei"},
    {"code": "BG", "name": "Bulgaria"},
    {"code": "BF", "name": "Burkina Faso"},
    {"code": "BI", "name": "Burundi"},
    {"code": "KH", "name": "Cambodia"},
    {"code": "CM", "name": "Cameroon"},
    {"code": "CA", "name": "Canada"},
    {"code": "CV", "name": "Cape Verde"},
    {"code": "CF", "name": "Central African Republic"},
    {"code": "TD", "name": "Chad"},
    {"code": "CL", "name": "Chile"},
    {"code": "CN", "name": "China"},
    {"code": "CO", "name": "Colombia"},
    {"code": "KM", "name": "Comoros"},
    {"code": "CG", "name": "Congo"},
    {"code": "CR", "name": "Costa Rica"},
    {"code": "HR", "name": "Croatia"},
    {"code": "CU", "name": "Cuba"},
    {"code": "CY", "name": "Cyprus"},
    {"code": "CZ", "name": "Czech Republic"},
    {"code": "DK", "name": "Denmark"},
    {"code": "DJ", "name": "Djibouti"},
    {"code": "DM", "name": "Dominica"},
    {"code": "DO", "name": "Dominican Republic"},
    {"code": "EC", "name": "Ecuador"},
    {"code": "EG", "name": "Egypt"},
    {"code": "SV", "name": "El Salvador"},
    {"code": "GQ", "name": "Equatorial Guinea"},
    {"code": "ER", "name": "Eritrea"},
    {"code": "EE", "name": "Estonia"},
    {"code": "ET", "name": "Ethiopia"},
    {"code": "FJ", "name": "Fiji"},
    {"code": "FI", "name": "Finland"},
    {"code": "FR", "name": "France"},
    {"code": "GA", "name": "Gabon"},
    {"code": "GM", "name": "Gambia"},
    {"code": "GE", "name": "Georgia"},
    {"code": "DE", "name": "Germany"},
    {"code": "GH", "name": "Ghana"},
    {"code": "GR", "name": "Greece"},
    {"code": "GD", "name": "Grenada"},
    {"code": "GT", "name": "Guatemala"},
    {"code": "GN", "name": "Guinea"},
    {"code": "GW", "name": "Guinea-Bissau"},
    {"code": "GY", "name": "Guyana"},
    {"code": "HT", "name": "Haiti"},
    {"code": "HN", "name": "Honduras"},
    {"code": "HU", "name": "Hungary"},
    {"code": "IS", "name": "Iceland"},
    {"code": "IN", "name": "India"},
    {"code": "ID", "name": "Indonesia"},
    {"code": "IR", "name": "Iran"},
    {"code": "IQ", "name": "Iraq"},
    {"code": "IE", "name": "Ireland"},
    {"code": "IL", "name": "Israel"},
    {"code": "IT", "name": "Italy"},
    {"code": "JM", "name": "Jamaica"},
    {"code": "JP", "name": "Japan"},
    {"code": "JO", "name": "Jordan"},
    {"code": "KZ", "name": "Kazakhstan"},
    {"code": "KE", "name": "Kenya"},
    {"code": "KI", "name": "Kiribati"},
    {"code": "KP", "name": "North Korea"},
    {"code": "KR", "name": "South Korea"},
    {"code": "KW", "name": "Kuwait"},
    {"code": "KG", "name": "Kyrgyzstan"},
    {"code": "LA", "name": "Laos"},
    {"code": "LV", "name": "Latvia"},
    {"code": "LB", "name": "Lebanon"},
    {"code": "LS", "name": "Lesotho"},
    {"code": "LR", "name": "Liberia"},
    {"code": "LY", "name": "Libya"},
    {"code": "LI", "name": "Liechtenstein"},
    {"code": "LT", "name": "Lithuania"},
    {"code": "LU", "name": "Luxembourg"},
    {"code": "MK", "name": "North Macedonia"},
    {"code": "MG", "name": "Madagascar"},
    {"code": "MW", "name": "Malawi"},
    {"code": "MY", "name": "Malaysia"},
    {"code": "MV", "name": "Maldives"},
    {"code": "ML", "name": "Mali"},
    {"code": "MT", "name": "Malta"},
    {"code": "MH", "name": "Marshall Islands"},
    {"code": "MR", "name": "Mauritania"},
    {"code": "MU", "name": "Mauritius"},
    {"code": "MX", "name": "Mexico"},
    {"code": "FM", "name": "Micronesia"},
    {"code": "MD", "name": "Moldova"},
    {"code": "MC", "name": "Monaco"},
    {"code": "MN", "name": "Mongolia"},
    {"code": "ME", "name": "Montenegro"},
    {"code": "MA", "name": "Morocco"},
    {"code": "MZ", "name": "Mozambique"},
    {"code": "MM", "name": "Myanmar"},
    {"code": "NA", "name": "Namibia"},
    {"code": "NR", "name": "Nauru"},
    {"code": "NP", "name": "Nepal"},
    {"code": "NL", "name": "Netherlands"},
    {"code": "NZ", "name": "New Zealand"},
    {"code": "NI", "name": "Nicaragua"},
    {"code": "NE", "name": "Niger"},
    {"code": "NG", "name": "Nigeria"},
    {"code": "NO", "name": "Norway"},
    {"code": "OM", "name": "Oman"},
    {"code": "PK", "name": "Pakistan"},
    {"code": "PW", "name": "Palau"},
    {"code": "PS", "name": "Palestine"},
    {"code": "PA", "name": "Panama"},
    {"code": "PG", "name": "Papua New Guinea"},
    {"code": "PY", "name": "Paraguay"},
    {"code": "PE", "name": "Peru"},
    {"code": "PH", "name": "Philippines"},
    {"code": "PL", "name": "Poland"},
    {"code": "PT", "name": "Portugal"},
    {"code": "QA", "name": "Qatar"},
    {"code": "RO", "name": "Romania"},
    {"code": "RU", "name": "Russia"},
    {"code": "RW", "name": "Rwanda"},
    {"code": "KN", "name": "Saint Kitts and Nevis"},
    {"code": "LC", "name": "Saint Lucia"},
    {"code": "VC", "name": "Saint Vincent and the Grenadines"},
    {"code": "WS", "name": "Samoa"},
    {"code": "SM", "name": "San Marino"},
    {"code": "ST", "name": "Sao Tome and Principe"},
    {"code": "SA", "name": "Saudi Arabia"},
    {"code": "SN", "name": "Senegal"},
    {"code": "RS", "name": "Serbia"},
    {"code": "SC", "name": "Seychelles"},
    {"code": "SL", "name": "Sierra Leone"},
    {"code": "SG", "name": "Singapore"},
    {"code": "SK", "name": "Slovakia"},
    {"code": "SI", "name": "Slovenia"},
    {"code": "SB", "name": "Solomon Islands"},
    {"code": "SO", "name": "Somalia"},
    {"code": "ZA", "name": "South Africa"},
    {"code": "SS", "name": "South Sudan"},
    {"code": "ES", "name": "Spain"},
    {"code": "LK", "name": "Sri Lanka"},
    {"code": "SD", "name": "Sudan"},
    {"code": "SR", "name": "Suriname"},
    {"code": "SZ", "name": "Swaziland"},
    {"code": "SE", "name": "Sweden"},
    {"code": "CH", "name": "Switzerland"},
    {"code": "SY", "name": "Syria"},
    {"code": "TW", "name": "Taiwan"},
    {"code": "TJ", "name": "Tajikistan"},
    {"code": "TZ", "name": "Tanzania"},
    {"code": "TH", "name": "Thailand"},
    {"code": "TL", "name": "Timor-Leste"},
    {"code": "TG", "name": "Togo"},
    {"code": "TO", "name": "Tonga"},
    {"code": "TT", "name": "Trinidad and Tobago"},
    {"code": "TN", "name": "Tunisia"},
    {"code": "TR", "name": "Turkey"},
    {"code": "TM", "name": "Turkmenistan"},
    {"code": "TV", "name": "Tuvalu"},
    {"code": "UG", "name": "Uganda"},
    {"code": "UA", "name": "Ukraine"},
    {"code": "AE", "name": "United Arab Emirates"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "US", "name": "United States"},
    {"code": "UY", "name": "Uruguay"},
    {"code": "UZ", "name": "Uzbekistan"},
    {"code": "VU", "name": "Vanuatu"},
    {"code": "VA", "name": "Vatican City"},
    {"code": "VE", "name": "Venezuela"},
    {"code": "VN", "name": "Vietnam"},
    {"code": "YE", "name": "Yemen"},
    {"code": "ZM", "name": "Zambia"},
    {"code": "ZW", "name": "Zimbabwe"},
]

COUNTRY_CODES = {country["code"] for country in COUNTRIES}

# ============================================================================
# Languages (ISO 639-1)
# ============================================================================

LANGUAGES: List[Dict[str, str]] = [
    {"code": "am", "name": "Amharic"},
    {"code": "ar", "name": "Arabic"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "zh", "name": "Chinese"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "nl", "name": "Dutch"},
    {"code": "en", "name": "English"},
    {"code": "et", "name": "Estonian"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fr", "name": "French"},
    {"code": "de", "name": "German"},
    {"code": "el", "name": "Greek"},
    {"code": "he", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "id", "name": "Indonesian"},
    {"code": "it", "name": "Italian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "ko", "name": "Korean"},
    {"code": "lv", "name": "Latvian"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "ms", "name": "Malay"},
    {"code": "no", "name": "Norwegian"},
    {"code": "fa", "name": "Persian"},
    {"code": "pl", "name": "Polish"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "sr", "name": "Serbian"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "es", "name": "Spanish"},
    {"code": "sw", "name": "Swahili"},
    {"code": "sv", "name": "Swedish"},
    {"code": "th", "name": "Thai"},
    {"code": "tr", "name": "Turkish"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "vi", "name": "Vietnamese"},
]

LANGUAGE_CODES = {lang["code"] for lang in LANGUAGES}

# ============================================================================
# Language Proficiency Levels (CEFR + Native)
# ============================================================================

PROFICIENCY_LEVELS: List[Dict[str, str]] = [
    {
        "code": "native",
        "name": "Native",
        "description": "Native or bilingual proficiency",
    },
    {"code": "c2", "name": "C2 - Mastery", "description": "Proficient user - Mastery"},
    {
        "code": "c1",
        "name": "C1 - Advanced",
        "description": "Proficient user - Effective operational proficiency",
    },
    {
        "code": "b2",
        "name": "B2 - Upper Intermediate",
        "description": "Independent user - Vantage",
    },
    {
        "code": "b1",
        "name": "B1 - Intermediate",
        "description": "Independent user - Threshold",
    },
    {"code": "a2", "name": "A2 - Elementary", "description": "Basic user - Waystage"},
    {"code": "a1", "name": "A1 - Beginner", "description": "Basic user - Breakthrough"},
]

PROFICIENCY_LEVEL_CODES = {level["code"] for level in PROFICIENCY_LEVELS}

# ============================================================================
# Phone Country Codes (ITU E.164)
# ============================================================================

PHONE_COUNTRY_CODES: List[Dict[str, str]] = [
    {"code": "+1", "country": "United States / Canada"},
    {"code": "+7", "country": "Russia / Kazakhstan"},
    {"code": "+20", "country": "Egypt"},
    {"code": "+27", "country": "South Africa"},
    {"code": "+30", "country": "Greece"},
    {"code": "+31", "country": "Netherlands"},
    {"code": "+32", "country": "Belgium"},
    {"code": "+33", "country": "France"},
    {"code": "+34", "country": "Spain"},
    {"code": "+36", "country": "Hungary"},
    {"code": "+39", "country": "Italy"},
    {"code": "+40", "country": "Romania"},
    {"code": "+41", "country": "Switzerland"},
    {"code": "+43", "country": "Austria"},
    {"code": "+44", "country": "United Kingdom"},
    {"code": "+45", "country": "Denmark"},
    {"code": "+46", "country": "Sweden"},
    {"code": "+47", "country": "Norway"},
    {"code": "+48", "country": "Poland"},
    {"code": "+49", "country": "Germany"},
    {"code": "+51", "country": "Peru"},
    {"code": "+52", "country": "Mexico"},
    {"code": "+53", "country": "Cuba"},
    {"code": "+54", "country": "Argentina"},
    {"code": "+55", "country": "Brazil"},
    {"code": "+56", "country": "Chile"},
    {"code": "+57", "country": "Colombia"},
    {"code": "+58", "country": "Venezuela"},
    {"code": "+60", "country": "Malaysia"},
    {"code": "+61", "country": "Australia"},
    {"code": "+62", "country": "Indonesia"},
    {"code": "+63", "country": "Philippines"},
    {"code": "+64", "country": "New Zealand"},
    {"code": "+65", "country": "Singapore"},
    {"code": "+66", "country": "Thailand"},
    {"code": "+81", "country": "Japan"},
    {"code": "+82", "country": "South Korea"},
    {"code": "+84", "country": "Vietnam"},
    {"code": "+86", "country": "China"},
    {"code": "+90", "country": "Turkey"},
    {"code": "+91", "country": "India"},
    {"code": "+92", "country": "Pakistan"},
    {"code": "+93", "country": "Afghanistan"},
    {"code": "+94", "country": "Sri Lanka"},
    {"code": "+95", "country": "Myanmar"},
    {"code": "+98", "country": "Iran"},
    {"code": "+212", "country": "Morocco"},
    {"code": "+213", "country": "Algeria"},
    {"code": "+216", "country": "Tunisia"},
    {"code": "+218", "country": "Libya"},
    {"code": "+220", "country": "Gambia"},
    {"code": "+221", "country": "Senegal"},
    {"code": "+222", "country": "Mauritania"},
    {"code": "+223", "country": "Mali"},
    {"code": "+224", "country": "Guinea"},
    {"code": "+225", "country": "Ivory Coast"},
    {"code": "+226", "country": "Burkina Faso"},
    {"code": "+227", "country": "Niger"},
    {"code": "+228", "country": "Togo"},
    {"code": "+229", "country": "Benin"},
    {"code": "+230", "country": "Mauritius"},
    {"code": "+231", "country": "Liberia"},
    {"code": "+232", "country": "Sierra Leone"},
    {"code": "+233", "country": "Ghana"},
    {"code": "+234", "country": "Nigeria"},
    {"code": "+235", "country": "Chad"},
    {"code": "+236", "country": "Central African Republic"},
    {"code": "+237", "country": "Cameroon"},
    {"code": "+238", "country": "Cape Verde"},
    {"code": "+239", "country": "Sao Tome and Principe"},
    {"code": "+240", "country": "Equatorial Guinea"},
    {"code": "+241", "country": "Gabon"},
    {"code": "+242", "country": "Congo"},
    {"code": "+243", "country": "DR Congo"},
    {"code": "+244", "country": "Angola"},
    {"code": "+245", "country": "Guinea-Bissau"},
    {"code": "+248", "country": "Seychelles"},
    {"code": "+249", "country": "Sudan"},
    {"code": "+250", "country": "Rwanda"},
    {"code": "+251", "country": "Ethiopia"},
    {"code": "+252", "country": "Somalia"},
    {"code": "+253", "country": "Djibouti"},
    {"code": "+254", "country": "Kenya"},
    {"code": "+255", "country": "Tanzania"},
    {"code": "+256", "country": "Uganda"},
    {"code": "+257", "country": "Burundi"},
    {"code": "+258", "country": "Mozambique"},
    {"code": "+260", "country": "Zambia"},
    {"code": "+261", "country": "Madagascar"},
    {"code": "+262", "country": "Reunion"},
    {"code": "+263", "country": "Zimbabwe"},
    {"code": "+264", "country": "Namibia"},
    {"code": "+265", "country": "Malawi"},
    {"code": "+266", "country": "Lesotho"},
    {"code": "+267", "country": "Botswana"},
    {"code": "+268", "country": "Swaziland"},
    {"code": "+269", "country": "Comoros"},
    {"code": "+290", "country": "Saint Helena"},
    {"code": "+291", "country": "Eritrea"},
    {"code": "+297", "country": "Aruba"},
    {"code": "+298", "country": "Faroe Islands"},
    {"code": "+299", "country": "Greenland"},
    {"code": "+350", "country": "Gibraltar"},
    {"code": "+351", "country": "Portugal"},
    {"code": "+352", "country": "Luxembourg"},
    {"code": "+353", "country": "Ireland"},
    {"code": "+354", "country": "Iceland"},
    {"code": "+355", "country": "Albania"},
    {"code": "+356", "country": "Malta"},
    {"code": "+357", "country": "Cyprus"},
    {"code": "+358", "country": "Finland"},
    {"code": "+359", "country": "Bulgaria"},
    {"code": "+370", "country": "Lithuania"},
    {"code": "+371", "country": "Latvia"},
    {"code": "+372", "country": "Estonia"},
    {"code": "+373", "country": "Moldova"},
    {"code": "+374", "country": "Armenia"},
    {"code": "+375", "country": "Belarus"},
    {"code": "+376", "country": "Andorra"},
    {"code": "+377", "country": "Monaco"},
    {"code": "+378", "country": "San Marino"},
    {"code": "+379", "country": "Vatican City"},
    {"code": "+380", "country": "Ukraine"},
    {"code": "+381", "country": "Serbia"},
    {"code": "+382", "country": "Montenegro"},
    {"code": "+383", "country": "Kosovo"},
    {"code": "+385", "country": "Croatia"},
    {"code": "+386", "country": "Slovenia"},
    {"code": "+387", "country": "Bosnia and Herzegovina"},
    {"code": "+389", "country": "North Macedonia"},
    {"code": "+420", "country": "Czech Republic"},
    {"code": "+421", "country": "Slovakia"},
    {"code": "+423", "country": "Liechtenstein"},
    {"code": "+500", "country": "Falkland Islands"},
    {"code": "+501", "country": "Belize"},
    {"code": "+502", "country": "Guatemala"},
    {"code": "+503", "country": "El Salvador"},
    {"code": "+504", "country": "Honduras"},
    {"code": "+505", "country": "Nicaragua"},
    {"code": "+506", "country": "Costa Rica"},
    {"code": "+507", "country": "Panama"},
    {"code": "+508", "country": "Saint Pierre and Miquelon"},
    {"code": "+509", "country": "Haiti"},
    {"code": "+590", "country": "Guadeloupe"},
    {"code": "+591", "country": "Bolivia"},
    {"code": "+592", "country": "Guyana"},
    {"code": "+593", "country": "Ecuador"},
    {"code": "+594", "country": "French Guiana"},
    {"code": "+595", "country": "Paraguay"},
    {"code": "+596", "country": "Martinique"},
    {"code": "+597", "country": "Suriname"},
    {"code": "+598", "country": "Uruguay"},
    {"code": "+599", "country": "Netherlands Antilles"},
    {"code": "+670", "country": "Timor-Leste"},
    {"code": "+672", "country": "Antarctica"},
    {"code": "+673", "country": "Brunei"},
    {"code": "+674", "country": "Nauru"},
    {"code": "+675", "country": "Papua New Guinea"},
    {"code": "+676", "country": "Tonga"},
    {"code": "+677", "country": "Solomon Islands"},
    {"code": "+678", "country": "Vanuatu"},
    {"code": "+679", "country": "Fiji"},
    {"code": "+680", "country": "Palau"},
    {"code": "+681", "country": "Wallis and Futuna"},
    {"code": "+682", "country": "Cook Islands"},
    {"code": "+683", "country": "Niue"},
    {"code": "+685", "country": "Samoa"},
    {"code": "+686", "country": "Kiribati"},
    {"code": "+687", "country": "New Caledonia"},
    {"code": "+688", "country": "Tuvalu"},
    {"code": "+689", "country": "French Polynesia"},
    {"code": "+690", "country": "Tokelau"},
    {"code": "+691", "country": "Micronesia"},
    {"code": "+692", "country": "Marshall Islands"},
    {"code": "+850", "country": "North Korea"},
    {"code": "+852", "country": "Hong Kong"},
    {"code": "+853", "country": "Macau"},
    {"code": "+855", "country": "Cambodia"},
    {"code": "+856", "country": "Laos"},
    {"code": "+880", "country": "Bangladesh"},
    {"code": "+886", "country": "Taiwan"},
    {"code": "+960", "country": "Maldives"},
    {"code": "+961", "country": "Lebanon"},
    {"code": "+962", "country": "Jordan"},
    {"code": "+963", "country": "Syria"},
    {"code": "+964", "country": "Iraq"},
    {"code": "+965", "country": "Kuwait"},
    {"code": "+966", "country": "Saudi Arabia"},
    {"code": "+967", "country": "Yemen"},
    {"code": "+968", "country": "Oman"},
    {"code": "+970", "country": "Palestine"},
    {"code": "+971", "country": "United Arab Emirates"},
    {"code": "+972", "country": "Israel"},
    {"code": "+973", "country": "Bahrain"},
    {"code": "+974", "country": "Qatar"},
    {"code": "+975", "country": "Bhutan"},
    {"code": "+976", "country": "Mongolia"},
    {"code": "+977", "country": "Nepal"},
    {"code": "+992", "country": "Tajikistan"},
    {"code": "+993", "country": "Turkmenistan"},
    {"code": "+994", "country": "Azerbaijan"},
    {"code": "+995", "country": "Georgia"},
    {"code": "+996", "country": "Kyrgyzstan"},
    {"code": "+998", "country": "Uzbekistan"},
]

PHONE_COUNTRY_CODE_VALUES = {code["code"] for code in PHONE_COUNTRY_CODES}


# ============================================================================
# Validation Helpers
# ============================================================================


def is_valid_country_code(code: str) -> bool:
    """Check if country code is valid."""
    return code in COUNTRY_CODES


def is_valid_language_code(code: str) -> bool:
    """Check if language code is valid."""
    return code in LANGUAGE_CODES


def is_valid_proficiency_level(level: str) -> bool:
    """Check if proficiency level is valid."""
    return level in PROFICIENCY_LEVEL_CODES


def is_valid_phone_country_code(code: str) -> bool:
    """Check if phone country code is valid."""
    return code in PHONE_COUNTRY_CODE_VALUES


def get_country_name(code: str) -> str:
    """Get country name from code."""
    for country in COUNTRIES:
        if country["code"] == code:
            return country["name"]
    return ""


def get_language_name(code: str) -> str:
    """Get language name from code."""
    for lang in LANGUAGES:
        if lang["code"] == code:
            return lang["name"]
    return ""
