# =============================================================================
# GitLab CI/CD Pipeline for TutorHub
# =============================================================================
#
# Features:
# - Parallel lint + test execution (non-blocking lints)
# - Auto-build and push on main/develop branches
# - Docker Hub registry integration
# - Cached image pulls for faster execution
#
# Required CI/CD Variables:
#   DOCKERHUB_TOKEN: Docker Hub access token
#   TEST_STUDENT_PASSWORD: E2E test credentials
#   TEST_TUTOR_PASSWORD: E2E test credentials
#   TEST_ADMIN_PASSWORD: E2E test credentials
#
# =============================================================================

stages:
  - validate      # Lint + Test in parallel (non-blocking lints)
  - build         # Build artifacts
  - docker        # Build + Push Docker images

# =============================================================================
# Global Configuration
# =============================================================================

variables:
  # Harbor Registry (proxy for Docker Hub images)
  HARBOR_REGISTRY: harbor.in.lazarev.cloud

  # Performance
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: "fast"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.cache/npm"

  # Database for tests
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: test_db
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_password
  REDIS_HOST: redis
  REDIS_PORT: "6379"

  # Docker Hub images
  DOCKERHUB_USER: va2mne
  FRONTEND_IMAGE: va2mne/tutorhub-frontend
  BACKEND_IMAGE: va2mne/tutorhub-backend

# Default settings
default:
  tags:
    - docker
    - linux
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# =============================================================================
# Cache Templates
# =============================================================================

.node_cache: &node_cache
  cache:
    key:
      files:
        - frontend-v2/package-lock.json
    paths:
      - frontend-v2/node_modules/
      - .cache/npm/
    policy: pull-push

.pip_cache: &pip_cache
  cache:
    key:
      files:
        - backend/requirements-dev.txt
    paths:
      - .cache/pip/
    policy: pull-push

# =============================================================================
# Docker Build Template
# =============================================================================

.docker-build:
  stage: docker
  image: ${HARBOR_REGISTRY}/proxy/docker:24-dind
  services:
    - name: ${HARBOR_REGISTRY}/proxy/docker:24-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - |
      echo "Waiting for Docker daemon..."
      for i in $(seq 1 30); do
        docker info >/dev/null 2>&1 && break
        sleep 2
      done
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin || true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
  allow_failure: true
  interruptible: false
  timeout: 30 minutes

# =============================================================================
# Stage: Validate (Lint + Test in parallel)
# =============================================================================

# --- Linting Jobs (all allow_failure: true) ---

lint:frontend:
  stage: validate
  image: ${HARBOR_REGISTRY}/proxy/node:20-alpine
  needs: []
  <<: *node_cache
  script:
    - cd frontend-v2
    - npm ci --prefer-offline --no-audit || true
    - npm run lint || true
    - npm run type-check || true
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 10 minutes

lint:backend:ruff:
  stage: validate
  image: ${HARBOR_REGISTRY}/proxy/python:3.12-slim
  needs: []
  script:
    - pip install --quiet ruff || true
    - cd backend && ruff check . || true
    - cd backend && ruff format --check . || true
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 5 minutes

lint:security:
  stage: validate
  image: ${HARBOR_REGISTRY}/proxy/python:3.12-slim
  needs: []
  script:
    - pip install --quiet bandit pip-audit || true
    - cd backend && bandit -r . -f txt -x ./tests || true
    - cd backend && pip install -q -r requirements-prod.txt && pip-audit || true
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 10 minutes

lint:npm-audit:
  stage: validate
  image: ${HARBOR_REGISTRY}/proxy/node:20-alpine
  needs: []
  script:
    - cd frontend-v2 && npm audit --audit-level=high || true
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 5 minutes

# --- Test Jobs (non-blocking) ---

test:frontend:unit:
  stage: validate
  image: ${HARBOR_REGISTRY}/proxy/node:20-alpine
  needs: []
  <<: *node_cache
  script:
    - cd frontend-v2
    - npm ci --prefer-offline --no-audit || true
    - npm run test:run || true
    - npm run test:coverage || true
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - frontend-v2/coverage/
    when: always
    expire_in: 7 days
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 15 minutes

test:frontend:e2e:
  stage: validate
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  needs: []
  <<: *node_cache
  variables:
    E2E_BASE_URL: "https://edustream.valsa.solutions"
    E2E_API_URL: "https://api.valsa.solutions/api/v1"
  script:
    - cd frontend-v2
    - npm ci --prefer-offline --no-audit || true
    - npx playwright install --with-deps chromium || true
    - npm run test:e2e:integration || true
  artifacts:
    paths:
      - frontend-v2/playwright-report/
      - frontend-v2/test-results/
    when: always
    expire_in: 30 days
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 20 minutes

test:backend:
  stage: validate
  image: ${HARBOR_REGISTRY}/proxy/python:3.12-slim
  needs: []
  <<: *pip_cache
  services:
    - name: ${HARBOR_REGISTRY}/proxy/postgres:17-alpine
      alias: postgres
    - name: ${HARBOR_REGISTRY}/proxy/redis:7-alpine
      alias: redis
  variables:
    DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}/0"
    TESTING: "true"
    SECRET_KEY: "test-secret-key-for-ci-pipeline-32chars"
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends postgresql-client || true
    - |
      echo "Waiting for PostgreSQL..."
      for i in $(seq 1 30); do
        pg_isready -h postgres -U $POSTGRES_USER && break
        sleep 2
      done || true
    - cd backend
    - pip install --quiet -r requirements-dev.txt || true
  script:
    - pytest tests/ -v --tb=short --junitxml=test-results/junit.xml || true
  coverage: '/TOTAL.*\s+(\d+%)/'
  artifacts:
    paths:
      - backend/test-results/
    reports:
      junit: backend/test-results/junit.xml
    when: always
    expire_in: 7 days
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 20 minutes

# =============================================================================
# Stage: Build
# =============================================================================

build:frontend:
  stage: build
  image: ${HARBOR_REGISTRY}/proxy/node:20-alpine
  needs:
    - job: test:frontend:unit
      optional: true
  <<: *node_cache
  variables:
    NEXT_PUBLIC_API_URL: "https://api.valsa.solutions/api/v1"
  script:
    - cd frontend-v2
    - npm ci --prefer-offline --no-audit || true
    - npm run build || true
  artifacts:
    paths:
      - frontend-v2/.next/
    expire_in: 1 hour
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 15 minutes

build:backend:
  stage: build
  image: ${HARBOR_REGISTRY}/proxy/python:3.12-slim
  needs:
    - job: test:backend
      optional: true
  <<: *pip_cache
  script:
    - cd backend
    - pip install --quiet -r requirements-prod.txt || true
    - python -c "import sys; print(f'Python {sys.version}')" || true
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
  timeout: 10 minutes

# =============================================================================
# Stage: Docker Build + Push
# =============================================================================

docker:frontend:
  extends: .docker-build
  needs:
    - job: build:frontend
      optional: true
    - job: test:frontend:unit
      optional: true
  allow_failure: true
  script:
    - |
      VERSION=${CI_COMMIT_SHORT_SHA}
      echo "Building frontend:$VERSION"
      docker build \
        -t $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA \
        -t $FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG \
        -t $FRONTEND_IMAGE:latest \
        -f frontend-v2/Dockerfile \
        ./frontend-v2 || true
      docker push $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA || true
      docker push $FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG || true
      docker push $FRONTEND_IMAGE:latest || true
      echo "Frontend build completed"

docker:backend:
  extends: .docker-build
  needs:
    - job: build:backend
      optional: true
    - job: test:backend
      optional: true
  allow_failure: true
  script:
    - |
      VERSION=${CI_COMMIT_SHORT_SHA}
      echo "Building backend:$VERSION"
      docker build \
        -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA \
        -t $BACKEND_IMAGE:$CI_COMMIT_REF_SLUG \
        -t $BACKEND_IMAGE:latest \
        -f backend/Dockerfile \
        ./backend || true
      docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA || true
      docker push $BACKEND_IMAGE:$CI_COMMIT_REF_SLUG || true
      docker push $BACKEND_IMAGE:latest || true
      echo "Backend build completed"

# =============================================================================
# Workflow Rules
# =============================================================================

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
