import { User, BookingDTO } from '@/types';

export const mockUser = (overrides: Partial<User> = {}): User => ({
  id: 1,
  email: 'test@example.com',
  role: 'student',
  is_active: true,
  is_verified: true,
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
  avatar_url: null,
  avatarUrl: null,
  currency: 'USD',
  timezone: 'UTC',
  first_name: 'John',
  last_name: 'Doe',
  country: null,
  bio: null,
  learning_goal: null,
  ...overrides,
});

export const mockBookings = (overrides: Partial<BookingDTO> = {}): BookingDTO => ({
  id: 1,
  tutor_profile_id: 1,
  student_id: 1,
  subject_id: 1,
  start_at: '2025-01-25T10:00:00Z',
  end_at: '2025-01-25T11:00:00Z',
  topic: 'Test Topic',
  notes: 'Test Notes',
  hourly_rate: 50,
  total_amount: 50,
  status: 'pending',
  meeting_url: null,
  pricing_option_id: null,
  pricing_type: null,
  subject_name: 'Mathematics',
  student_name: 'John Doe',
  student: {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
  },
  tutor_earnings_cents: 5000,
  lesson_type: 'regular',
  student_timezone: 'UTC',
  created_at: '2025-01-01T00:00:00Z',
  updated_at: '2025-01-01T00:00:00Z',
  ...overrides,
});